# Generated by Django 4.1.6 on 2023-03-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_event_interested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='interested',
            field=models.IntegerField(default=0),
        ),
    ]
