# Generated by Django 4.1.6 on 2023-03-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
